---
- name: install webserver components
  hosts: webserver
  become: true
  tasks:
    - name: Install packages
      package:
        name: "{{item}}"
        state: present
      loop:
      - libapache2-mod-wsgi
      - python-pip
      - python-virtualenv
